### ISSUE TITLE
Selecting the moving image facet checkbox is returning no search results

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#158] opened 2020-10-08 22:02 UTC
## Describe the bug
Selecting the moving image checkbox in facets does not return any results.

## To reproduce
1. Search for something with moving image material in the results like "act up".
2. Open filters and select "moving image" under format. 
3. See the search results.

## Error message or screenshots
Selecting the moving image checkbox results in a 500 error in the console.

**Comment by helrond** [comment] 2020-10-09 13:11
OK this turned out to be two things, both in Argo:
- the 500 error was being produced when no min or max dates were present, fixed by a928ab701d6d11fb7e4c87cf095ad1c97cd65c4f
- the lack of results for `moving_image` objects was caused by filtering on the wrong field (Text field instead of Keyword field), fixed by 5751d8d051c473aa287e7924310c7daba912fbd6

**Closed as completed by helrond** 2020-10-09 13:11 UTC
Labels: bug, search
